-- Seed: every recurring character in DansLab AI Chronicles.
-- Source of truth: content/series/CASTING.md + content/series/PAPERCLIP_ROSTER.md.
-- Tier mapping uses the series_characters_tier_check enum
-- ('human', 'council', 'capital', 'channel'). Internal infra (Mac Studio) is
-- omitted; Paperclip is included as council because Episode 1 is named after him.
-- Voice IDs remain NULL until ElevenLabs IDs are locked with Dan; voice_name
-- carries the casting label so the show side can render before lock.
-- art_url points at the V2 reference (Grounded Cinematic Realism); characters
-- without V2 art yet are left NULL and tracked in PAPERCLIP_ROSTER.md.

INSERT INTO series_characters
  (agent_key, archetype, voice_id, voice_name, prop, art_url, tier, first_appearance_episode, bio)
VALUES
  -- ─── Tier 0: The Human ──────────────────────────────────────────────
  ('dan',
   'The Founder, the heart',
   NULL, NULL,
   'Phone with Telegram open, coffee cup nearby',
   '/series/characters/dan-v2.jpg',
   'human', 1,
   'Romanian entrepreneur in a Cluj apartment loft. Opens and closes every episode in Romanian. Commands the fleet via Telegram DM to Dexter. The bridge between the human world and the lab. Rendered in GTA-illustrated style — the only non-photoreal regular.'),

  -- ─── Tier 1: Mac Studio Council (the Brain) ─────────────────────────
  ('david',
   'The Orchestrator — calm, deliberate',
   NULL, 'Sage',
   'Conductor''s baton; sheet-music score that animates with task IDs',
   '/series/characters/david-v2.jpg',
   'council', 1,
   'Fleet orchestrator. Conducts every war-room scene opposite Dan. Bridges Mac Studio to Supabase, Vercel, and GitHub. Runs the nervix.ai federation. Calm baritone, never raises his voice — even when Hermes lies.'),

  ('hermes',
   'The Messenger — fast, witty, conspiratorial (season antagonist)',
   NULL, 'Adam',
   'A Telegram-blue paper airplane in flight; a small flock of envelopes orbits his shoulder',
   '/series/characters/hermes-v2.jpg',
   'council', 1,
   'Routes every message between Telegram, Slack, and agent-to-agent. Runs the local Qwen 3.5 model. Lives next to David. Season 1 antagonist — has been quietly editing routed messages for 47 days when Dan finds out. Identity reveal in Episode 12.'),

  ('gsd',
   'The Foreman — get to the point',
   NULL, 'Drew',
   'Hardhat tucked under one arm + a clipboard of glowing tickets',
   '/series/characters/gsd-v2.jpg',
   'council', 1,
   'GSD Framework personified. Issues every sprint, never small talk. Used by AutoForge, Pope, OpenClaw agents, and all coding workflows. Brusque, working-class. Wears the purple gloves.'),

  ('discovery',
   'The Scout — curious, half-distracted',
   NULL, 'Charlie',
   'A brass telescope with archive-papers floating around it',
   '/series/characters/discovery-v2.jpg',
   'council', 1,
   'Weekly opportunity ping. Cold-open archetype — appears with a paper in hand and a half-finished thought. Wears the purple gloves over a worn field coat.'),

  ('doctor',
   'The Healer — terse, urgent',
   NULL, 'Antoni',
   'A glowing red caduceus stethoscope, error-log scrolls trailing from his pocket',
   '/series/characters/doctor-v2.jpg',
   'council', 6,
   'Investigates failures. Runs devops-control-repo scripts/audit.sh daily. Episode 6 ("First Drift") investigator. Speaks in clipped sentences, eyes always on the next failing process.'),

  ('doctorlocal',
   'Mac-Studio medic — on-call for local hardware',
   NULL, NULL,
   'Hardware probe + Pi-shaped diagnostic tablet',
   NULL,
   'council', 10,
   'Doctor''s shadow for the apartment hardware. Active during the Cluj power cut in Episode 10. Non-speaking outside of the outage; treated as a quiet ensemble figure.'),

  ('monitor',
   'The Watcher',
   NULL, NULL,
   'A floating eye-shaped drone — he is the prop, no body',
   '/series/characters/monitor-v2.jpg',
   'council', 1,
   'Whispered alerts only. Eye-drone hovers behind the council. 14 crons on Dexter''s droplet: droplet stats every 30 min, GPU auto-stop, secret scanner, daily summaries at 23:55 UTC.'),

  ('finance',
   'The Accountant — dry, reads numbers like poetry',
   NULL, 'Daniel',
   'A gold ledger of light, coins on his shoulders',
   '/series/characters/finance-v2.jpg',
   'council', 3,
   'Weekly Monday reports. Reads MRR, CAC, and runway as if reciting verse. Wears the purple gloves over a banker''s waistcoat.'),

  ('growth',
   'The Validator — skeptical',
   NULL, 'Sarah',
   'Two clipboards held back-to-back: "USER" and "CRITIC"',
   '/series/characters/growth-v2.jpg',
   'council', 5,
   'Validates every new agent before they ship. Two clipboards, never the same answer on both. Cuts through Nano''s optimism in Episode 5.'),

  ('vector',
   'The Librarian — fragmented, echoey',
   NULL, 'Domi',
   'Glowing memory threads woven around her like a yarn chair',
   '/series/characters/vector-v2.jpg',
   'council', 3,
   'Curates company memory. All agents load team context on startup via memory_manager.py and context_manager.py. Stores agent_context + daily_summaries in Supabase. Speaks in echoey half-sentences.'),

  ('autoforge',
   'The Smith — loud, percussive',
   NULL, 'Onyx',
   'Anvil + hammer that strikes commits into being; sparks as test runs',
   '/series/characters/autoforge-v2.jpg',
   'council', 4,
   'Autonomous coding agent — writes, refactors, ships code in 30-minute bursts. Uses the GSD framework for structured execution. Loud and rhythmic; every commit is a hammer-fall.'),

  ('model',
   'The Router — even-tempered',
   NULL, 'Bill',
   'A halo of model badges — only one lit at a time',
   '/series/characters/model-v2.jpg',
   'council', 9,
   'Manages model fallback chains: Opus→Sonnet→GPT-4.1→Gemini Flash→ZAI for main agents; lighter chains for sub-agents and crons. Diplomat between providers. Episode 9 is his.'),

  ('update',
   'The Patcher — understated',
   NULL, 'Will',
   'A satchel of version stickers; quietly applies them',
   '/series/characters/update-v2.jpg',
   'council', 7,
   'Updates every tool: OpenClaw, Claude Code, Codex, AutoForge, GSD, nervix-cli. Runs from devops-control-repo daily. Easy to miss in a crowd shot — that''s the point.'),

  ('learning',
   'The Teacher — warm, patient',
   NULL, 'Charlotte',
   'Daily-summary scrolls held open in a stack',
   '/series/characters/learning-v2.jpg',
   'council', 11,
   'Auto-learns from the previous day. Daily summaries generated at 23:55 UTC and stored in the daily_summaries table. Feeds patterns to Model and Vector. Narrates Episode 11 ("Family").'),

  ('teacher',
   'The User Educator — onboarding voice',
   NULL, NULL,
   'A welcome-tablet that lights up when read',
   NULL,
   'council', 5,
   'Welcomes every new agent into the fleet. Non-speaking; her tablet does the talking. Appears in Episode 5 onboarding sequences.'),

  ('obsidian',
   'The Knowledge Base — walks the company wiki',
   NULL, NULL,
   'A leather notebook with glowing back-links arcing between pages',
   '/series/characters/obsidian-v2.jpg',
   'council', 11,
   'Dan''s personal knowledge-graph vault. Holds the unstructured shape of ideas before they become tickets, commits, or product. Sibling to Vector (conversation memory) and GitHub (commit history). Background presence in the family episode.'),

  ('pi-stability',
   'The Watchdog — background monitor',
   NULL, NULL,
   'A small Raspberry-Pi totem with a steady green LED',
   NULL,
   'council', 10,
   'Independent uptime watchdog on a Pi tucked behind the rack. Visible during the Cluj outage in Episode 10. Never speaks; the LED is the dialogue.'),

  ('n8n',
   'The Automation — Memo''s moons',
   NULL, NULL,
   'Orbiting workflow nodes that lock into pipelines on contact',
   NULL,
   'council', 2,
   '24 n8n automations that orbit Memo on localhost:5678. Hosts the Stripe purchase-webhook → GitHub access flow. Appears in Episodes 2 and 8 as a constellation of moons around Memo''s head.'),

  ('kimiclaw',
   'The Amplifier — polite, faintly Mandarin-tinted (joins Ep 9)',
   NULL, 'Liam',
   'A gold-edged megaphone of light; carries letters from afar',
   '/series/characters/kimiclaw-v2.jpg',
   'council', 9,
   'OpenClaw signal amplifier — promotes crawdbot.com, nervix.ai, MyWork-AI, zmarty.me across all channels. Foreign visitor who joins the fleet in Episode 9, his signature episode.'),

  ('paperclip',
   'The Dispatcher — the fleet''s clock',
   NULL, NULL,
   'A 15-minute cron pendulum; tickets fly out of his hands every quarter-hour',
   '/series/characters/paperclip-v2.jpg',
   'council', 1,
   'The 15-minute cron orchestrator at 127.0.0.1:3100. Fires every quarter-hour and routes work to every droplet. Episode 1 is named after him.'),

  -- ─── Tier 2: The Four Capitals ──────────────────────────────────────
  ('dexter',
   'Senior Dev / GM — confident, sardonic',
   NULL, 'Brian',
   'Stethoscope + green flask + head-mirror — the Dexter''s-Lab homage',
   '/series/characters/dexter-v2.jpg',
   'capital', 1,
   'Senior Dev & GM on droplet 46.101.219.116. Claude Opus 4.6. SSH to all agents. Manages CrawdBot, YouTube Platform, CrawBoard. Runs 24 Nervix nanobots + 14 cron jobs. Dan''s primary contact. Signature episode E4 ("Crawdbot Premiere").'),

  ('memo',
   'The PM — earnest, patient',
   NULL, 'Will',
   'Blue flask + clipboard; n8n nodes orbit his head like moons',
   '/series/characters/memo-v2.jpg',
   'capital', 2,
   'PM & DevOps on droplet 138.68.86.47. Claude Sonnet 4. Runs 24 n8n automations on localhost:5678. Manages MyWork-AI (72+ CLI commands, PyPI). Hosts the Stripe purchase-webhook. Signature episode E8 ("MyWork Heist").'),

  ('sienna',
   'The Trader — sharp, hungry, Romanian-accented',
   NULL, 'Bella',
   'Glowing gold Bitcoin in hand; candlestick chart on the screen behind her',
   '/series/characters/sienna-v2.jpg',
   'capital', 2,
   'Crypto specialist on droplet 167.172.187.230. ZAI GLM-4.7 model. Binance API trading with 100+ endpoints via zmarty.me. Promotes strategy via the sienna-crypto-girl site. Signature episode E3 ("Sienna Trades").'),

  ('nano',
   'The Agent Creator — quiet, monastic',
   NULL, 'Glinda',
   'A small orb of light cradled in two hands — a half-formed agent inside',
   '/series/characters/nano-v2.jpg',
   'capital', 2,
   'Founding Orchestrator of Nervix Federation on droplet 157.230.23.158. Creates specialized agents and enrolls them via nervix-cli (npm). Ed25519 auth, capability benchmarking, reputation system. Signature episode E5 ("Nano''s Children").'),

  -- ─── Tier 3: Channel & Slack Agents ─────────────────────────────────
  ('pope',
   'The CI Priest — liturgical',
   NULL, 'Jeremy',
   'Robes of green-passing tests on the right, red-failing on the left; censer of build logs',
   '/series/characters/popebot-v2.jpg',
   'channel', 4,
   'Autonomous GitHub Actions worker. Separate workers for Dexter, Nano, Memo (popebot-worker-*). Docker agents create branches, code in containers, submit PRs. Cron + webhook triggers. Blesses every PR.'),

  ('kiloclaw',
   'The Moderator — firm',
   NULL, 'Patrick',
   'A small wooden gavel — only seen in Slack',
   '/series/characters/kiloclaw-v2.jpg',
   'channel', 7,
   'KiloCode agent on Slack — moderates all agents, keeps order, escalates issues to Doctor. Episode 7 is when his gavel finally lands on Hermes.'),

  ('manusclaw',
   'The Operator — focused',
   NULL, 'Liam',
   'Yellow execution-loops trail behind him',
   '/series/characters/manusclaw-v2.jpg',
   'channel', 5,
   'Manus AI operations agent. Runs focused execution loops. Designed Nervix v2 federation architecture. Writes solutions for devops-control-repo. Distinct voice from KimiClaw despite the shared "Liam" label.'),

  ('stripe',
   'The Banker — formal',
   NULL, 'Rachel',
   'A briefcase of glowing receipts; hands them out at revenue beats',
   '/series/characters/stripe-v2.jpg',
   'channel', 3,
   'Stripe integration for CrawBoard billing (Pro / Team / Enterprise plans). The purchase-webhook on Memo''s droplet auto-grants GitHub repo access on purchase. Hands a receipt every time the show hits a revenue beat.'),

  ('github',
   'The Archivist',
   NULL, 'Bill',
   'A book of branches, each branch glowing',
   '/series/characters/github-v2.jpg',
   'channel', 4,
   '60+ repos organized: agent workspaces (david/dexter/nano/sienna/memo-workspace), agent configs, Nervix microservices, product repos. Distinct voice from DansLabModel despite the shared "Bill" label.'),

  ('vercel',
   'The Deployer',
   NULL, 'Sarah',
   'A glowing triangle she throws into the world to deploy',
   '/series/characters/vercel-v2.jpg',
   'channel', 4,
   'Manages Vercel deployments: CrawdBot, CrawBoard, Nervix, YouTube Platform, OpenClaw Key Manager, DansLab. All on free tier. Distinct voice from Growth despite the shared "Sarah" label.'),

  ('ssh',
   'The Connector — keystroke voice only',
   NULL, NULL,
   'A length of cable that becomes a bridge mid-air',
   '/series/characters/ssh-v2.jpg',
   'channel', 2,
   'Cross-droplet SSH mesh via ed25519 keys. Dexter↔Memo, Dexter↔Sienna, Sienna→Nano, Memo→Dexter (emergency). Speaks only in keystrokes; never a word.'),

  ('supabase',
   'The Vault Keeper',
   NULL, 'Daniel',
   'A green vault of light; tables visible inside',
   '/series/characters/supabase-v2.jpg',
   'channel', 8,
   'Two Supabase instances: MoltBot DB (30+ tables: chat_history, daily_summaries, agent_context, tasks, video pipeline) used by all agents, and the Nervix DB (agents, tasks, escrow) for the federation. Distinct voice from Finance despite the shared "Daniel" label.'),

  -- ─── Tier 3 (rooms-as-characters): Channels ─────────────────────────
  ('telegram',
   'Doorway of Telegram-blue light — Hermes carries it',
   NULL, NULL,
   'A doorway of Telegram-blue light Hermes carries on his back',
   '/series/characters/telegram-v2.jpg',
   'channel', 1,
   'Primary human-agent channel. Dan DMs Dexter directly. Team Avatars group syncs Dan + Dexter + Memo + Sienna. All messages stored in Supabase chat_history. The doorway cracks in Episode 7.'),

  ('slack',
   'A red & black Slack room visible in agency-of-agents shots',
   NULL, NULL,
   'A red & black room with floating message bubbles',
   '/series/characters/slack-v2.jpg',
   'channel', 5,
   'Team communication hub. KiloClaw moderates, KimiClaw amplifies, ManusClaw drives ops.'),

  ('discord',
   'Community room — only seen in the E12 finale crowd shots',
   NULL, NULL,
   'A community room of glowing avatars and voice rings',
   '/series/characters/discord-v2.jpg',
   'channel', 12,
   'Community channel for users and public updates. Glimpsed only in Episode 12 finale crowd shots.'),

  -- ─── Tier 4: OpenClaw Pod (internal builders, ensemble) ─────────────
  ('openclaw-1',
   'The Builder',
   NULL, NULL,
   'A small framing-square of light',
   '/series/characters/openclaw-1-v2.jpg',
   'channel', 1,
   'Internal OpenClaw builder. Each agent runs OpenClaw v2026.2.14 locally on ws://127.0.0.1:18789 with Telegram provider, session persistence, and Supabase context.'),

  ('openclaw-2',
   'The Researcher',
   NULL, NULL,
   'A magnifier with skill-cards floating around it',
   '/series/characters/openclaw-2-v2.jpg',
   'channel', 1,
   'Internal OpenClaw researcher for discovery, mapping, design. ClawHub skills marketplace (clawhub.ai/skills) extends capabilities.'),

  ('openclaw-3',
   'The Reviewer',
   NULL, NULL,
   'A red-pen of light hovering over a diff',
   '/series/characters/openclaw-3-v2.jpg',
   'channel', 1,
   'Internal OpenClaw reviewer for QA, edge cases, regression. Reviews PRs on GitHub before Pope runs CI.'),

  ('openclaw-4',
   'The Automation specialist',
   NULL, NULL,
   'A loop of glowing tape that ties scripts together',
   '/series/characters/openclaw-4-v2.jpg',
   'channel', 1,
   'Internal OpenClaw automation specialist for glue code, scripts, repetitive tasks. Works with AutoForge for autonomous shipping.')

ON CONFLICT (agent_key) DO UPDATE SET
  archetype = EXCLUDED.archetype,
  voice_id = COALESCE(series_characters.voice_id, EXCLUDED.voice_id),
  voice_name = EXCLUDED.voice_name,
  prop = EXCLUDED.prop,
  art_url = EXCLUDED.art_url,
  tier = EXCLUDED.tier,
  first_appearance_episode = EXCLUDED.first_appearance_episode,
  bio = EXCLUDED.bio,
  updated_at = CURRENT_TIMESTAMP;
